-- 1. USER PROFILES TABLE (Role-Based Access Control)
-- Roles: 'principal' (Superadmin), 'staff_admin' (Admissions/Faculty), 'student' (Data Entry Contributor)
CREATE TABLE IF NOT EXISTS public.user_profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  role TEXT NOT NULL CHECK (role IN ('principal', 'staff_admin', 'student')),
  title TEXT,
  campus_id TEXT,
  grade TEXT,
  avatar_url TEXT,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_user_profiles_role ON public.user_profiles(role);
CREATE INDEX IF NOT EXISTS idx_user_profiles_email ON public.user_profiles(email);

-- Enable RLS for Profiles
ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

-- Users can read their own profile
CREATE POLICY "Users read own profile" ON public.user_profiles
  FOR SELECT TO authenticated
  USING ((select auth.uid()) = id);

-- Principals and staff can read all profiles
CREATE POLICY "Staff and Principal read all profiles" ON public.user_profiles
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  );

-- Principals can manage (insert/update/delete) all profiles
CREATE POLICY "Principals manage all profiles" ON public.user_profiles
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role = 'principal'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role = 'principal'
    )
  );

-- Staff can insert and update student profiles only
CREATE POLICY "Staff manage student profiles" ON public.user_profiles
  FOR INSERT TO authenticated
  WITH CHECK (
    role = 'student' AND EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role = 'staff_admin'
    )
  );

CREATE POLICY "Staff update student profiles" ON public.user_profiles
  FOR UPDATE TO authenticated
  USING (
    role = 'student' AND EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role = 'staff_admin'
    )
  )
  WITH CHECK (
    role = 'student' AND EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role = 'staff_admin'
    )
  );

-- ------------------------------------------------------------------------------
-- 2. CAMPUSES TABLE (3 in Yangon & 1 in Mawlamyine)
CREATE TABLE IF NOT EXISTS public.campuses (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL CHECK (city IN ('Yangon', 'Mawlamyine')),
  tagline TEXT NOT NULL,
  address TEXT NOT NULL,
  phone TEXT NOT NULL,
  email TEXT NOT NULL,
  office_hours TEXT NOT NULL DEFAULT 'Mon–Sat: 08:30 AM – 05:00 PM',
  grades_served TEXT NOT NULL,
  facilities TEXT[] NOT NULL DEFAULT '{}',
  image_url TEXT NOT NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_campuses_city ON public.campuses(city);
CREATE INDEX IF NOT EXISTS idx_campuses_active ON public.campuses(is_active);

-- Enable RLS
ALTER TABLE public.campuses ENABLE ROW LEVEL SECURITY;

-- Campuses Policies: Public can read active campuses, Principal and staff admins can edit
CREATE POLICY "Public read active campuses" ON public.campuses
  FOR SELECT TO anon, authenticated
  USING (is_active = true);

CREATE POLICY "Staff and Principal manage campuses" ON public.campuses
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  );

-- ------------------------------------------------------------------------------
-- 3. YEARBOOK ALUMNI TABLE (With Student Submission & Review Workflow)
CREATE TABLE IF NOT EXISTS public.yearbook_alumni (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('Class of 2026', 'Class of 2025', 'Class of 2024')),
  role TEXT NOT NULL,
  destination TEXT NOT NULL,
  subjects TEXT NOT NULL,
  quote TEXT NOT NULL,
  image TEXT NOT NULL,
  badge TEXT,
  status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('published', 'pending_review', 'archived')),
  submitted_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  reviewer_notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_yearbook_category ON public.yearbook_alumni(category);
CREATE INDEX IF NOT EXISTS idx_yearbook_status ON public.yearbook_alumni(status);

-- Enable RLS
ALTER TABLE public.yearbook_alumni ENABLE ROW LEVEL SECURITY;

-- Public can read only published yearbook alumni
CREATE POLICY "Public read published yearbook alumni" ON public.yearbook_alumni
  FOR SELECT TO anon, authenticated
  USING (status = 'published');

-- Students can read their own submissions (even if pending)
CREATE POLICY "Students read own yearbook submissions" ON public.yearbook_alumni
  FOR SELECT TO authenticated
  USING (submitted_by = (select auth.uid()));

-- Students can insert submissions with status = 'pending_review'
CREATE POLICY "Students submit yearbook entry for review" ON public.yearbook_alumni
  FOR INSERT TO authenticated
  WITH CHECK (
    status = 'pending_review' AND submitted_by = (select auth.uid())
  );

-- Staff and Principal have full management of yearbook alumni
CREATE POLICY "Staff and Principal manage all yearbook alumni" ON public.yearbook_alumni
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  );

-- ------------------------------------------------------------------------------
-- 4. CLUBS & SOCIETIES TABLE (With Student Activity Proposals)
CREATE TABLE IF NOT EXISTS public.clubs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN ('STEM & Tech', 'Academic & Debate', 'STEM & Science', 'Creative Arts', 'Sports & Fitness')),
  icon TEXT NOT NULL DEFAULT 'groups',
  members TEXT NOT NULL DEFAULT '25+ Scholars',
  meeting_time TEXT NOT NULL,
  leadership TEXT NOT NULL,
  description TEXT NOT NULL,
  image TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'published' CHECK (status IN ('published', 'pending_review', 'archived')),
  submitted_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_clubs_category ON public.clubs(category);
CREATE INDEX IF NOT EXISTS idx_clubs_active ON public.clubs(is_active);
CREATE INDEX IF NOT EXISTS idx_clubs_status ON public.clubs(status);

-- Enable RLS
ALTER TABLE public.clubs ENABLE ROW LEVEL SECURITY;

-- Public can read active, published clubs
CREATE POLICY "Public read active published clubs" ON public.clubs
  FOR SELECT TO anon, authenticated
  USING (is_active = true AND status = 'published');

-- Students can insert club proposals
CREATE POLICY "Students propose club activities" ON public.clubs
  FOR INSERT TO authenticated
  WITH CHECK (
    status = 'pending_review' AND submitted_by = (select auth.uid())
  );

-- Staff and Principal can manage all clubs
CREATE POLICY "Staff and Principal manage clubs" ON public.clubs
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  );

-- ------------------------------------------------------------------------------
-- 4. ADMISSIONS APPLICATIONS TABLE
CREATE TABLE IF NOT EXISTS public.admissions (
  id TEXT PRIMARY KEY,
  student_name TEXT NOT NULL,
  date_of_birth DATE,
  gender TEXT CHECK (gender IN ('Male', 'Female', 'Other')),
  nationality TEXT DEFAULT 'Myanmar',
  grade TEXT NOT NULL,
  program_level TEXT,
  academic_stream TEXT,
  selected_subjects TEXT[] DEFAULT '{}',
  intended_start_term TEXT,
  study_mode TEXT DEFAULT 'Full-Time On-Campus',
  previous_school TEXT,
  parent_name TEXT,
  relationship TEXT DEFAULT 'Parent',
  parent_email TEXT NOT NULL,
  parent_phone TEXT NOT NULL,
  address TEXT,
  emergency_contact TEXT,
  medical_notes TEXT,
  how_heard TEXT DEFAULT 'School Website',
  submitted_date TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Assessment Scheduled', 'Approved', 'Declined')),
  assessment_date TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_admissions_status ON public.admissions(status);
CREATE INDEX IF NOT EXISTS idx_admissions_grade ON public.admissions(grade);
CREATE INDEX IF NOT EXISTS idx_admissions_created ON public.admissions(created_at DESC);

-- Enable RLS
ALTER TABLE public.admissions ENABLE ROW LEVEL SECURITY;

-- Anyone can submit an admission application (INSERT)
CREATE POLICY "Public can submit admission application" ON public.admissions
  FOR INSERT TO anon, authenticated
  WITH CHECK (true);

-- Only authenticated Principal and Staff Administrators can view, update, and manage confidential applications
CREATE POLICY "Staff and Principal manage admissions" ON public.admissions
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  );

-- ------------------------------------------------------------------------------
-- 5. CLASSES & COURSES TABLE
CREATE TABLE IF NOT EXISTS public.classes_courses (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  code TEXT NOT NULL,
  grade TEXT NOT NULL CHECK (grade IN ('Lower Secondary (Year 7–9)', 'Pearson IGCSE', 'Pearson IAL')),
  category TEXT NOT NULL CHECK (category IN ('STEM', 'Business', 'Computing', 'Languages')),
  time TEXT NOT NULL,
  instructor TEXT NOT NULL,
  room TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX IF NOT EXISTS idx_classes_grade ON public.classes_courses(grade);
CREATE INDEX IF NOT EXISTS idx_classes_category ON public.classes_courses(category);

-- Enable RLS
ALTER TABLE public.classes_courses ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read classes" ON public.classes_courses
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "Staff and Principal manage classes" ON public.classes_courses
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  );

-- ------------------------------------------------------------------------------
-- 6. BULLETIN NOTICES TABLE
CREATE TABLE IF NOT EXISTS public.bulletin_notices (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  date TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('Official Notice', 'Academic', 'General')),
  content TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Enable RLS
ALTER TABLE public.bulletin_notices ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public read bulletin notices" ON public.bulletin_notices
  FOR SELECT TO anon, authenticated
  USING (true);

CREATE POLICY "Staff and Principal manage bulletin notices" ON public.bulletin_notices
  FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.user_profiles p
      WHERE p.id = (select auth.uid()) AND p.role IN ('principal', 'staff_admin')
    )
  );

-- ==============================================================================
-- INITIAL SEED DATA
-- ==============================================================================

-- 1. SEED CAMPUSES (3 in Yangon & 1 in Mawlamyine)
INSERT INTO public.campuses (id, name, city, tagline, address, phone, email, office_hours, grades_served, facilities, image_url, is_active)
VALUES
  (
    'ywarma-campus',
    'Ywarma Campus',
    'Yangon',
    'Flagship Academic Center & Pearson Examination Hall',
    'No. 23B, Ywar Ma Kyaung Lane, Hlaing Township, Yangon, Myanmar (11051)',
    '+95 9 894 332200 / +95 9 894 332211',
    'ywarma.admissions@hinthar.education',
    'Mon–Sat: 08:30 AM – 05:00 PM',
    'Year 7–9 · Pearson IGCSE · Pearson IAL',
    ARRAY['Pearson Exam Center', 'Turing Computer Lab', 'Newton Physics & Chemistry Labs', 'British Council Testing Suite', 'Auditorium & Library'],
    '/images/heroImg.png',
    true
  ),
  (
    'shwe-padauk-campus',
    'Shwe Padauk Campus',
    'Yangon',
    'Senior STEM & Robotics Innovation Center',
    'Shwe Padauk Road, Yangon, Myanmar',
    '+95 9 894 332222',
    'shwepadauk@hinthar.education',
    'Mon–Sat: 08:30 AM – 05:00 PM',
    'Pearson IGCSE & Pearson IAL (STEM Specialized)',
    ARRAY['AI & Robotics Studio', 'Advanced Chemistry Lab', 'Bio-Science Incubator', 'Collaborative Study Pods', 'Student Recreation Hub'],
    '/images/specialisations/stemSpecialisation.png',
    true
  ),
  (
    'shwe-pone-nyet-campus',
    'Shwe Pone Nyet Campus',
    'Yangon',
    'Lower Secondary & Creative Arts Hub',
    'Shwe Pone Nyet Street, Yangon, Myanmar',
    '+95 9 894 332233',
    'shweponenyet@hinthar.education',
    'Mon–Sat: 08:30 AM – 05:00 PM',
    'Lower Secondary (Year 7–9) & Foundation Arts',
    ARRAY['Digital Media Lab', 'Music & Performing Arts Studio', 'Badminton & Fitness Arena', 'Language Immersion Lounge', 'Junior Science Hub'],
    '/images/specialisations/creativeSpecialisation.png',
    true
  ),
  (
    'mawlamyine-campus',
    'Mawlamyine Campus',
    'Mawlamyine',
    'Mon State Regional Center of Academic Excellence',
    'Main Strand Road, Mawlamyine, Mon State, Myanmar',
    '+95 9 894 332288 / +95 32 202 888',
    'mawlamyine@hinthar.education',
    'Mon–Sat: 08:30 AM – 05:00 PM',
    'Year 7–9 · Pearson IGCSE · Pearson IAL',
    ARRAY['Full-Scale Science Labs', 'Computer Lab & Fiber Network', 'Extensive British Library', 'Multi-Purpose Sports Court', 'Hostel Facilities'],
    '/images/specialisations/businessSpecialisation.png',
    true
  )
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  city = EXCLUDED.city,
  tagline = EXCLUDED.tagline,
  address = EXCLUDED.address,
  phone = EXCLUDED.phone,
  email = EXCLUDED.email,
  grades_served = EXCLUDED.grades_served,
  facilities = EXCLUDED.facilities,
  image_url = EXCLUDED.image_url;

-- (Seed data for Yearbook, Clubs, Classes, and Bulletins cleaned as requested)

