tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "error": "#ba1a1a",
                "on-secondary": "#ffffff",
                "inverse-on-surface": "#f1f0f8",
                "primary-container": "#254aa5",
                "secondary-fixed-dim": "#d7ca00",
                "outline": "#747683",
                "on-primary-container": "#aec1ff",
                "on-error": "#ffffff",
                "background": "#faf8ff",
                "tertiary-fixed-dim": "#ffb68f",
                "tertiary": "#622800",
                "surface": "#faf8ff",
                "on-primary-fixed": "#00174b",
                "surface-tint": "#3659b4",
                "on-primary-fixed-variant": "#18409b",
                "on-secondary-fixed-variant": "#4d4800",
                "inverse-primary": "#b4c5ff",
                "surface-variant": "#e2e2ea",
                "tertiary-fixed": "#ffdbca",
                "secondary-container": "#f3e300",
                "on-secondary-container": "#6b6400",
                "on-tertiary-fixed-variant": "#773200",
                "on-tertiary-container": "#ffb086",
                "secondary-fixed": "#f6e600",
                "on-surface-variant": "#444652",
                "neutral-surface": "#F8F9FA",
                "on-error-container": "#93000a",
                "secondary": "#676000",
                "inverse-surface": "#2f3036",
                "error-container": "#ffdad6",
                "on-surface": "#1a1b21",
                "surface-bright": "#faf8ff",
                "oxford-blue": "#14213D",
                "primary": "#00328b",
                "on-primary": "#ffffff",
                "surface-container-lowest": "#ffffff",
                "tertiary-container": "#863900",
                "on-tertiary": "#ffffff",
                "primary-fixed": "#dbe1ff",
                "academic-gold": "#E5B80B",
                "surface-container-low": "#f4f3fb",
                "surface-container-high": "#e8e7f0",
                "surface-container": "#eeedf5",
                "surface-container-highest": "#e2e2ea",
                "on-background": "#1a1b21",
                "outline-variant": "#c4c6d4",
                "surface-dim": "#dad9e1",
                "primary-fixed-dim": "#b4c5ff",
                "on-tertiary-fixed": "#331100",
                "on-secondary-fixed": "#1f1c00"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "margin-mobile": "16px",
                "section-padding-mobile": "48px",
                "container-max-width": "1200px",
                "section-padding-desktop": "80px",
                "stack-lg": "32px",
                "stack-sm": "8px",
                "gutter": "24px",
                "stack-md": "16px"
            },
            "fontFamily": {
                "body-lg": ["Libre Franklin"],
                "caption": ["Libre Franklin"],
                "label-caps": ["Manrope"],
                "headline-md": ["Manrope"],
                "display-hero": ["Manrope"],
                "body-md": ["Libre Franklin"],
                "headline-lg-mobile": ["Manrope"],
                "headline-lg": ["Manrope"]
            },
            "fontSize": {
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "caption": ["12px", {"lineHeight": "1.4", "fontWeight": "400"}],
                "label-caps": ["14px", {"lineHeight": "1.2", "letterSpacing": "0.05em", "fontWeight": "700"}],
                "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
                "display-hero": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "headline-lg-mobile": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                "headline-lg": ["32px", {"lineHeight": "1.3", "fontWeight": "600"}]
            }
        },
    },
}